services:
  mysql:
    image:
      mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: testeDb
      MYSQL_USER: dev
      MYSQL_PASSWORD: teste123
