services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-auth
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data


volumes:
  mysql_data:
  redis_data:
