name: Java CI Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test Java Application
    runs-on: ubuntu-latest

    steps:
      # Checkout do código da branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache do Maven para acelerar builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Setup do JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Sobe os serviços com Docker Compose
      - name: Start Docker Compose
        run: docker compose -f ./docker/docker-compose.yaml up -d

      # Compila e executa os testes
      - name: Build and Test
        run: mvn clean verify

      # Verifica estilo de código
     # - name: Run Checkstyle
      #  run: mvn checkstyle:check

      # Gera o .jar final
      - name: Build JAR file
        run: mvn package -DskipTests

      # Encerra os containers
      - name: Stop Docker Compose
        if: always()
        run: docker compose -f ./docker/docker-compose.yaml down

